#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
set -eu
# The generated config is disposable. This entry point and lock.json are inputs.
. ./nia-image.env
export SOURCE_DATE_EPOCH TZ=UTC
volume=$(printf 'NIAOS_%s_%s' "$NIA_RELEASE" "$NIA_ARCHITECTURE" | tr '[:lower:].-' '[:upper:]__')
lb config noauto --ignore-system-defaults \
    --mode debian --distribution "$NIA_CODENAME" --architectures "$NIA_ARCHITECTURE" \
    --binary-image iso-hybrid --image-name "niaos-$NIA_RELEASE" \
    --archive-areas "$NIA_ARCHIVE_AREAS" \
    --debootstrap-options '--include=ca-certificates' \
    --mirror-bootstrap "http://snapshot.debian.org/archive/debian/$NIA_SNAPSHOT/" \
    --mirror-chroot "http://snapshot.debian.org/archive/debian/$NIA_SNAPSHOT/" \
    --mirror-chroot-security "http://snapshot.debian.org/archive/debian-security/$NIA_SNAPSHOT/" \
    --mirror-debian-installer "https://snapshot.debian.org/archive/debian/$NIA_SNAPSHOT/" \
    --parent-mirror-debian-installer "https://snapshot.debian.org/archive/debian/$NIA_SNAPSHOT/" \
    --mirror-binary https://deb.debian.org/debian/ \
    --mirror-binary-security https://security.debian.org/debian-security/ \
    --security true --updates true \
    --apt-secure true --apt-recommends true --apt-indices false \
    --bootloaders "$NIA_BOOTLOADERS" --uefi-secure-boot "$NIA_SECURE_BOOT" \
    --linux-flavours amd64 --debian-installer "$NIA_INSTALLER" \
    --debian-installer-distribution "$NIA_CODENAME" --debian-installer-gui true \
    --bootappend-live 'boot=live components username=niaos hostname=niaos locales=ja_JP.UTF-8 keyboard-layouts=jp console=tty0 console=ttyS0,115200n8' \
    --iso-application 'NiaOS Debian 13 derivative' \
    --iso-publisher 'NiaOS development project' --iso-volume "$volume" \
    --checksums sha256 --memtest none --win32-loader false \
    --chroot-squashfs-compression-type zstd --chroot-squashfs-compression-level 15 \
    --source false --utc-time true "$@"
. config/bootstrap
test "$LB_PARENT_MIRROR_DEBIAN_INSTALLER" = "https://snapshot.debian.org/archive/debian/$NIA_SNAPSHOT/"
# lb config rewrites config/common; append the supported tool setting afterwards.
printf '%s\n' 'MKSQUASHFS_OPTIONS="-processors 1 -mem 512M"' >> config/common
