# SPDX-License-Identifier: BSD-3-Clause
# Deliberately scoped. This does not type-check all privileged Python modules.
[mypy]
python_version = 3.13
platform = linux
strict = True
warn_unreachable = True
disallow_any_expr = True
disallow_any_explicit = True
disallow_any_unimported = True
