# SPDX-License-Identifier: BSD-3-Clause
"""Build/check standard PO/POT/MO catalogs using GNU gettext, not a PO parser.

Run with --write after editing source or translations. The default checks all
generated bytes and complete, non-fuzzy coverage of every bundled catalog without changing them.
"""
import argparse
import ast
import gettext
import io
from pathlib import Path
import re
import subprocess
import tempfile

from i18n import DOMAIN, placeholders, display_text, catalog_candidates

ROOT = Path(__file__).resolve().parent
SOURCES = ('i18n.py', 'diagnostics.py', 'package_cli.py', 'management_grammar.py', 'interim_commands.py', 'interim_download.py', 'media.py', 'management_client.py')


def source_forms():
    result = {}
    for name in SOURCES:
        for node in ast.walk(ast.parse((ROOT / name).read_text())):
            if not isinstance(node, ast.Call):
                continue
            function = node.func.id if isinstance(node.func, ast.Name) else node.func.attr if isinstance(node.func, ast.Attribute) else ''
            if function == 'require' and (len(node.args) < 2 or not isinstance(node.args[1], ast.Call)
                    or not isinstance(node.args[1].func, ast.Name) or node.args[1].func.id != 'N_'):
                raise ValueError('unmarked public argument diagnostic in ' + name)
            count = 2 if function in ('plural', 'context') else 1 if function in ('N_', 'message', 'UsageError') else 0
            if not count or len(node.args) < count or not all(isinstance(a, ast.Constant) and isinstance(a.value, str) for a in node.args[:count]):
                continue
            values = [a.value for a in node.args[:count]]
            key = '\x04'.join(values) if function == 'context' else values[0]
            plural = values[1] if function == 'plural' else None
            if key in result and result[key] != plural:
                raise ValueError('message reused with a different plural form: ' + key)
            result[key] = plural
    return result


def check(write=False):
    env = {'PATH': '/usr/bin:/bin', 'LANG': 'C.UTF-8', 'LC_ALL': 'C.UTF-8', 'TZ': 'UTC'}
    with tempfile.TemporaryDirectory(prefix='nia-translations-') as temporary:
        pot = Path(temporary) / (DOMAIN + '.pot')
        subprocess.run(['xgettext', '--language=Python', '--from-code=UTF-8', '--keyword=',
            '--keyword=N_:1', '--keyword=message:1', '--keyword=plural:1,2', '--keyword=UsageError:1',
            '--keyword=context:1c,2',
            '--no-location', '--package-name=' + DOMAIN, '--package-version=1',
            '--copyright-holder=NiaOS contributors', '-o', str(pot), *SOURCES], cwd=ROOT, env=env, check=True)
        # The timestamp is not a translation input. Keep generated output stable.
        raw = re.sub(rb'^"POT-Creation-Date: .*\\n"\n', b'', pot.read_bytes(), flags=re.M)
        expected = source_forms()
        target = ROOT / 'po' / (DOMAIN + '.pot')
        if write:
            target.write_bytes(raw)
        elif target.read_bytes() != raw:
            raise ValueError('POT differs; run native/i18n_catalogs.py --write')
        count = 0
        for source in sorted((ROOT / 'po').glob('*.po')):
            language = source.stem
            if not catalog_candidates(language) or catalog_candidates(language)[0] != language or '.' in language:
                raise ValueError('invalid translation language name')
            if re.search(r'^#,.*\bfuzzy\b', source.read_text(), re.M):
                raise ValueError('fuzzy translation: ' + language)
            output = Path(temporary) / (language + '.mo')
            subprocess.run(['msgfmt', '--check', '--check-format', '--endianness=little',
                            '-o', str(output), str(source)], check=True, env=env)
            compiled = output.read_bytes()
            catalog = gettext.GNUTranslations(io.BytesIO(compiled))
            if catalog.info().get('language') != language:
                raise ValueError('catalog language metadata differs: ' + language)
            # Inspect the compiled catalog in this build checker only. Runtime
            # uses public gettext APIs. Missing/obsolete/fuzzy entries fail CI.
            keys = {key[0] if isinstance(key, tuple) else key for key in catalog._catalog if key != ''}
            if keys != set(expected):
                raise ValueError(f'{language}: translation keys differ: missing={sorted(set(expected)-keys)}, extra={sorted(keys-set(expected))}')
            for message, plural in expected.items():
                if (message in catalog._catalog) != (plural is None):
                    raise ValueError('translation pluralization differs: ' + message)
                entries = [value for key, value in catalog._catalog.items()
                           if key == message or isinstance(key, tuple) and key[0] == message]
                source = message.split('\x04', 1)[-1]
                if plural is not None and placeholders(source) != placeholders(plural):
                    raise ValueError('source plural placeholders differ')
                for translated in entries:
                    if not translated or placeholders(source) != placeholders(translated):
                        raise ValueError('invalid translated placeholders: ' + message)
                    if display_text(translated).replace('\\u000a', '\n').replace('\\u0009', '\t') != translated:
                        raise ValueError('hidden or control character in translation: ' + message)
            target = ROOT / 'locale' / language / 'LC_MESSAGES' / (DOMAIN + '.mo')
            if write:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(compiled)
            elif target.read_bytes() != compiled:
                raise ValueError('compiled translation differs: ' + language)
            count += 1
        if count == 0:
            raise ValueError('no translations')
        print(f'Checked {len(expected)} messages in {count} translation catalog(s).')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    check(parser.parse_args().write)
