#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Observe generated multi-owner roots in an explicitly disposable privileged VM."""
import argparse
from decimal import Decimal
import fcntl
import hashlib
import io
import json
import os
from pathlib import Path
import stat
import subprocess
import tarfile
import tempfile
import time


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('worker', 'target-base', 'inputs', 'report'):
        parser.add_argument('--' + name, required=True, type=Path)
    args = parser.parse_args()
    if os.getuid() != 0 or os.geteuid() != 0:
        parser.error('requires a disposable privileged VM')
    planned = json.loads((args.inputs / 'report.json').read_text())
    assert planned['result'] == 'pass' and len(planned['cases']) == 8
    results = []
    verified = {}
    allowed = {'.', 'alpha', 'alpha/beta'} | {
        stem + suffix for suffix in ('a', 'b') for stem in ('alpha/beta/file-', 'alias-', 'chain-', 'sym-')}
    for case in planned['cases']:
        assert case['case'] in range(8)
        path = args.inputs / f"order-{case['case']}.tar"
        assert path.stat().st_size <= 1024 * 1024
        raw = path.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        assert digest == case['archive'] and case['entries'] == 11
        if digest in verified:
            verified[digest]['source_owner_cases'].append(case['case'])
            continue  # Identical generated bytes need only one physical execution.
        with tarfile.open(fileobj=io.BytesIO(raw), mode='r:') as archive:
            members = archive.getmembers()
            names = [item.name.removeprefix('./').rstrip('/') or '.' for item in members]
            assert len(names) == len(set(names)) == 11 and set(names) == allowed
            assert names[:3] == ['.', 'alpha', 'alpha/beta']
            with tempfile.TemporaryDirectory(prefix='order-', dir=args.target_base) as temporary:
                parent = Path(temporary)
                target = parent / 'root'; target.mkdir(mode=0o700)
                source = parent / 'input.tar'; source.write_bytes(raw)
                f = os.open(source, os.O_RDONLY | os.O_CLOEXEC)
                d = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
                lease = os.open(parent / 'writer.lock', os.O_RDWR | os.O_CREAT | os.O_EXCL, 0o600)
                try:
                    fcntl.flock(lease, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    deadline = int(time.clock_gettime(time.CLOCK_BOOTTIME) * 1000) + 60000
                    result = subprocess.run([str(args.worker), digest, str(len(raw)), '11', str(deadline),
                        str(f), str(d), str(lease)], pass_fds=(f, d, lease), capture_output=True, text=True, timeout=65)
                finally:
                    os.close(lease); os.close(d); os.close(f)
                assert result.returncode == 0 and not result.stderr, (case['case'], result)
                assert json.loads(result.stdout) == dict(result='extracted', profile='linux-inode-v1',
                    archive_sha256=digest, entries=11, published=False)
                seen = set()
                for item, name in zip(members, names, strict=True):
                    actual = (target / name).lstat()
                    if item.islnk():
                        link = item.linkname.removeprefix('./')
                        assert link in seen
                        other = (target / link).lstat()
                        assert (actual.st_dev, actual.st_ino) == (other.st_dev, other.st_ino)
                    else:
                        assert (stat.S_IMODE(actual.st_mode), actual.st_uid, actual.st_gid) == (item.mode, item.uid, item.gid)
                        stamp = Decimal(item.pax_headers.get('mtime', str(item.mtime))) * 1000000000
                        assert stamp == int(stamp) and actual.st_mtime_ns == int(stamp)
                        if item.isdir():
                            assert stat.S_ISDIR(actual.st_mode)
                        elif item.issym():
                            assert stat.S_ISLNK(actual.st_mode) and os.readlink(target / name) == item.linkname
                        else:
                            assert item.isfile() and stat.S_ISREG(actual.st_mode)
                            assert (target / name).read_bytes() == archive.extractfile(item).read()
                    seen.add(name)
                record = dict(source_owner_cases=[case['case']], archive=digest, entries=11,
                    actual_parent_directories=True, numeric_attributes=True, exact_content=True,
                    negative_nanosecond_mtime=True, hardlink_chains=True)
                results.append(record); verified[digest] = record
    assert sorted(case for record in results for case in record['source_owner_cases']) == list(range(8))
    args.report.write_text(json.dumps(dict(result='pass', cases=results, published=False,
        production_authorization=False, actual_boot=False), indent=2) + '\n')
    print(f'PASS real root extraction: {len(results)} distinct archive(s) covering eight source-owner combinations')


if __name__ == '__main__':
    main()
